version: '3.7'

services: 
    production:
        hostname: go_actions_production
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
            target: prod
        environment:
            SERVING_PORT: "*:8080"
        volumes: 
            - .:/app
        ports:
            - "8080:8080"
        command: bash -c "go mod download & go build -o /bin/app . && /bin/app"

    development:
        hostname: go_actions_development
        container_name: go_actions_development
        depends_on: 
            - postgres
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
            target: dev
        environment:
            DEBUG: "true"
            SERVING_PORT: "*:8080"
            DB_HOST: localhost
        volumes: 
            - .:/app
        working_dir: /app
        ports:
            - "8080:8080"
        command: bash -c "go mod download & make watch"
        env_file:
            - .env
        network_mode: host

    postgres:
        image: postgres:11
        container_name: go_actions_db
        volumes:
            - go_actions:/var/libs/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=developer
            - POSTGRES_DB=go_actions_db
            - POSTGRES_PORT=5432
        ports:
            - 5432:5432
        networks:
            - net

volumes:
    go_actions:

networks:
    net:
        driver: bridge
