name: lint

on:
    push:
        branchs:
            - master

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Install go
              uses: actions/setup-go@v2
              id: go
              with:
                  go-versions: 1.13.x

            - name: Checkout code
              uses: actions/checkout@v2
              
            - name: Install golangci-lint
              run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.18.0

            - name: Run golangci-lint
              run: $(go env GOPATH)/bin/golangci-lint run
